---
title: "Basic Simulation in R"
author: "William Murrah"
date: ""
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r, include=FALSE}
# Don't delete this chunk if you are using the mosaic package
# This loads the mosaic and dplyr packages
require(mosaic)
```

```{r, include=FALSE}
# Some customization.  You can alter or delete as desired (if you know what you are doing).

# This changes the default colors in lattice plots.
trellis.par.set(theme=theme.mosaic())  

# knitr settings to control how R chunks work.
require(knitr)
opts_knit$set(root.dir = "../../")
opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
# This loads the mosaic data sets.  (Could be deleted if you are not using them.)
require(mosaicData)                
```

## Why do I need to know how to simulate data?


## Probability Distributions

In R, enter the following code into the console:

```{r, eval=FALSE}
?distributions
```

```{r} 
set.seed(082184) # Set the seed for reproducible results
# Use the CDF to calculate the probability a random draw will be less than or equal to a given number
pnorm(1.645)
dnorm(1.5) # Use the PDF to calculate the density
qnorm(.95) # Use the inverse CDF to calculate distribution values from quantiles
rnorm(10) # Random draws
```

### Binomial Example
```{r}
set.seed(19445)
# Use the CDF to calculate the probability of fewer than 10 successes
pbinom(10, 50, .2)
dbinom(17, 50, .2) # Use the PDF to calculate the probability of observing a value of 17
qbinom(.5, 50, .2) # Use the inverse CDF to calculate distribution values from quantiles 
rbinom(10, 50, .2) # Random draws
```


$$
y = \beta_0 + \beta_1 x_1 + \epsilon 
$$



### Session Information

  
```{r echo=FALSE}
sessionInfo()  # could use devtools::session_info() if you prefer that
```
  